### ISSUE TITLE
Rebind F10 key (to F12?) for SRV camera as it conflicts with screenshot

### ISSUE THREAD

**Issue by dmmartinez** [jamsoft/CMDJamski-T16000M-FCS-HOTAS#2]

**Comment by jamsoft** [comment]
Sorry I'm only just seen this, will have a play and look into that. Thanks for the suggestion.

**Comment by jamsoft** [comment]
After having looked into this F10 seems like a good solution as is. By default (as is mine currently set) F12 is the default Steam screenshot shortcut.

I think you may have moved your Steam screenshot shortcut to F10? I'm going to close this as I feel the current setup hits the mark for the majority of users.
