### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by StrasnyLada** [jamsoft/CMDJamski-T16000M-FCS-HOTAS#3]
Hello, 
I have followed the installation instructions and I'm getting this problem:
the game sets keyboard + mouse as default and ignores the joystick unless I choose the Thrustmaster T.16000M FCS HOTAS from the controls menu, but this sets the default Thrustmaster bindings.
In the installation menu appears a BindingLoadingErrors.log with following content:

> There where errors when loading preset file: CMDJamski-T16000M-FCS-HOTAS-V1.0.2.0.binds
> parsing XML, line 43: not well-formed (invalid token)
> There where errors when loading preset file: Custom.2.0.binds
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283
> Failed to find GUID for device: 046DC283

and the StartPreset.start changes content to "keyboard + mouse"

Any idea where the problem might be?

**Comment by jamsoft** [comment]
I've not seen anything like that. I've just updated the binding file so you might want to update and see if that helps. Other than that I think this is specific to your machine I'm afraid.
